#!/bin/bash

display_usage() { 
	echo -e "\nUsage:\n$0 [signature file ] [file to verify] \n"
	}

# if less than two arguments supplied, display usage 
	if [  $# -le 1 ] 
	then 
		display_usage
		exit 1
	fi

gpg --verify $1 $2
