#!/bin/bash

display_usage() { 
	echo -e "\nUsage:\n$0 [output file] [file to sign] \n"
	}

# if less than two arguments supplied, display usage 
	if [  $# -le 1 ] 
	then 
		display_usage
		exit 1
	fi

gpg --output $1 --detach-sig $2
