#!/bin/bash
# gpgtricks by stephan@stephan.ws
# 2014-06-18	0.1	initial release

# echo the usage
usage_f ()
{
	echo ""
	echo $"usage:		$0 {command}"
	echo "" 
	echo "commands:	detach [sigfile.sig] [inputfile]"
        echo "		verify [sigfile.sig] [inputfile]"
	echo "		export [keyid]"
	echo "		sign [sender id] [receiver id] [inputfile]"
	echo ""
}

# main functions
detach_f () {
	gpg --output "$1" --detach-sig "$2"
}
verify_f () {
	gpg --verify "$1" "$2"
}
export_f () {
	gpg -a --export "$1"
}
sign_f () {
	gpg -u "$1" -r "$2" --armor --sign --encrypt "$3"
}

# execute
case "$1" in
  detach)
	detach_f "$2" "$3"
	;;
  verify)
	verify_f "$2" "$3"
	;;
  export)
	export_f "$2"
	;;
  sign)
	sign_f "$2" "$3" "$4"
	;;
  *)
	usage_f
	exit 2
esac

# EOF
