#!/bin/bash
# gpgtricks by stephan@stephan.ws
# 2014-06-18	0.1	initial release

# echo the usage
usage_f ()
{
	echo ""
	echo $"usage:		$0 {command}"
	echo "" 
	echo "commands:	detach-sig [sigfile.sig] [inputfile]"
        echo "		verify-sig [sigfile.sig] [inputfile]"
	echo "		export-key [keyid]"
	echo "		sign [sender id] [receiver id] [inputfile]"
	echo ""
}

# main functions
detach-sig_f () {
	gpg --output "$1" --detach-sig "$2"
}
verify-sig_f () {
	gpg --verify "$1" "$2"
}
export-key_f () {
	gpg -a --export "$1"
}
sign_f () {
	gpg -u $1 -r $2 --armor --sign --encrypt $3
}

# execute
case "$1" in
  detach-sig)
	detach-sig_f "$2" "$3"
	;;
  verify-sig)
	verify-sig_f "$2" "$3"
	;;
  export-key)
	export-key_f "$2"
	;;
  sign)
	sign_f "$2" "$3" "$4"
	;;
  *)
	usage_f
	exit 2
esac

# EOF
